# Funksiya va Ml

# Data bilan tanishuv

In [5]:
import pandas as pd 
df=pd.read_csv('user_music_listen_data.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   User_ID       453 non-null    str
 1   T_Swift       444 non-null    float64
 2   Drake         439 non-null    float64
 3   Queen         441 non-null    float64
 4   The_Weeknd    442 non-null    float64
 5   Eminem        444 non-null    float64
 6   Nirvana       435 non-null    float64
 7   Ed_Sheeran    449 non-null    float64
 8   T_Scott       441 non-null    float64
 9   Linkin_Park   443 non-null    float64
 10  Dua_Lipa      445 non-null    float64
 11  K_Lamar       438 non-null    float64
 12  Imag_Dragons  439 non-null    float64
 13  Ariana_G      440 non-null    float64
dtypes: float64(13), str(1)
memory usage: 49.7 KB

In [7]:
df.isnull().sum()

User_ID          0
T_Swift          9
Drake           14
Queen           12
The_Weeknd      11
Eminem           9
Nirvana         18
Ed_Sheeran       4
T_Scott         12
Linkin_Park     10
Dua_Lipa         8
K_Lamar         15
Imag_Dragons    14
Ariana_G        13
dtype: int64

In [8]:
df = df.drop("User_ID", axis=1)

In [9]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype == 'object':
                df[col] = df[col].fillna(df[col].mode()[0])
            else:
                df[col] = df[col].fillna(df[col].mean())
    return df

In [10]:
toldir(df)

     T_Swift      Drake  Queen  ...  K_Lamar  Imag_Dragons  Ariana_G
0       53.0   0.000000   87.0  ...     49.0         212.0     112.0
1      144.0  60.148064   53.0  ...     47.0         232.0     157.0
2        0.0  47.000000   64.0  ...    103.0         199.0     176.0
3      136.0  45.000000    0.0  ...     73.0         190.0     111.0
4      110.0  33.000000   52.0  ...     66.0         124.0      66.0
..       ...        ...    ...  ...      ...           ...       ...
448     66.0   0.000000   82.0  ...     22.0         301.0       0.0
449    208.0   0.000000   40.0  ...     47.0         170.0     165.0
450     36.0  40.000000   42.0  ...     13.0         164.0      62.0
451     74.0  19.000000   63.0  ...     39.0         227.0     113.0
452      0.0  60.148064    0.0  ...    129.0          63.0      25.0

[453 rows x 13 columns]

In [11]:
df.isnull().sum()

T_Swift         0
Drake           0
Queen           0
The_Weeknd      0
Eminem          0
Nirvana         0
Ed_Sheeran      0
T_Scott         0
Linkin_Park     0
Dua_Lipa        0
K_Lamar         0
Imag_Dragons    0
Ariana_G        0
dtype: int64

# Scaling

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaler=MinMaxScaler()

In [14]:
scaler

MinMaxScaler()

In [17]:
num_cols= df.columns

In [18]:
df[num_cols] = scaler.fit_transform(df[num_cols])

In [19]:
df.head()

    T_Swift     Drake     Queen  ...   K_Lamar  Imag_Dragons  Ariana_G
0  0.141711  0.000000  0.283388  ...  0.174377      0.452026  0.449799
1  0.385027  0.149251  0.172638  ...  0.167260      0.494670  0.630522
2  0.000000  0.116625  0.208469  ...  0.366548      0.424307  0.706827
3  0.363636  0.111663  0.000000  ...  0.259786      0.405117  0.445783
4  0.294118  0.081886  0.169381  ...  0.234875      0.264392  0.265060

[5 rows x 13 columns]