data preporcessingdan 4 ta basic ca xar biriga 5 ta follow up tuzing

yangi dataset toping va classification va regression alohida aloxida k foldni toping

In [1]:
import pandas as pd 
df = pd.read_csv("/Users/sherzodbeksharobiddinov/MLFoundation/Sherzod_dev/2-oy_Model_Building/Data/Chocolate Sales (2).csv")
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   object
 1   Country        3282 non-null   object
 2   Product        3282 non-null   object
 3   Date           3282 non-null   object
 4   Amount         3282 non-null   object
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), object(5)
memory usage: 154.0+ KB

In [3]:
df.drop(['Date', 'Sales Person'], axis=1, inplace=True)

In [4]:
def datalarni_toldir(data):
    for col in data.columns:
        if data[col].isnull().any():
            if data[col].dtype == "object":
                data[col].fillna(data[col].mode()[0], inplace=True)
            else:
                data[col].fillna(data[col].mean(), inplace=True)
    return data

df = datalarni_toldir(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country        3282 non-null   object
 1   Product        3282 non-null   object
 2   Amount         3282 non-null   object
 3   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), object(3)
memory usage: 102.7+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder

def labella_funksiya(data):
    le = LabelEncoder()
    for ustun in data.columns:
        # Faqat matnli (object) ustunlarni tanlaymiz
        if data[ustun].dtype == 'object':
            # Har bir matnli ustunni raqamga o'giramiz
            data[ustun] = le.fit_transform(data[ustun].astype(str)) # astype(str) xatolikni oldini oladi
    return data

# Funksiyani chaqiramiz
df = labella_funksiya(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country        3282 non-null   int64
 1   Product        3282 non-null   int64
 2   Amount         3282 non-null   int64
 3   Boxes Shipped  3282 non-null   int64
dtypes: int64(4)
memory usage: 102.7 KB

In [6]:
from sklearn.preprocessing import StandardScaler

raqamli_ustun = df.select_dtypes(include = ['int64','float64']).columns
standard_scaler = StandardScaler()
df[raqamli_ustun] = standard_scaler.fit_transform(df[raqamli_ustun])

df.head()

    Country   Product    Amount  Boxes Shipped
0  0.901197  0.510364  0.450387       0.123648
1 -0.253940 -1.343553  1.187331      -0.569868
2 -0.253940  0.973843  0.162770      -0.594061
3 -1.409078  0.973843 -1.052378       1.430038
4  0.901197  0.973843 -0.981918       0.155904

## model Selection

In [7]:
from sklearn.model_selection import KFold, cross_val_score
target_column = 'Amount'
X = df.drop(target_column, axis=1)
y = df[target_column]

kf = KFold(n_splits = 5, shuffle=True, random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression, LinearRegression

logistic_model = LogisticRegression(random_state=42)
linear_model = LinearRegression()

scores = cross_val_score(linear_model, X, y, cv=kf, scoring='r2')
print("R2 natijalar:", scores)
print("O'rtacha R2:", scores.mean())

R2 natijalar: [-0.00211842  0.00390471  0.00341643 -0.00314923 -0.00051813]
O'rtacha R2: 0.0003070694472841806