# Linear Regression

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')

# Data bilan tanishuv

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 647.0 KB

In [4]:
# drop_cols = ['date','street','city','statezip','country']

In [5]:
df.drop(['date'],axis=1,inplace=True)
df.drop(['street'],axis=1,inplace=True)
df.drop(['city'],axis=1,inplace=True)
df.drop(['statezip'],axis=1,inplace=True)
df.drop(['country'],axis=1,inplace=True)

In [6]:
df.nunique()

price            1741
bedrooms           10
bathrooms          26
sqft_living       566
sqft_lot         3113
floors              6
waterfront          2
view                5
condition           5
sqft_above        511
sqft_basement     207
yr_built          115
yr_renovated       60
dtype: int64

In [7]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

dataset Linear Regression uchun to'gri keladi faqat Data preprocessing qilish kerak

price target qiymat

# Data Preprocessing

In [8]:
df.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
dtype: int64

# Tushib qolgan qiymatlar yo'q ekan shuning uchun birdan Encodingga o'tamiz

# Encoding

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
dtypes: float64(4), int64(9)
memory usage: 467.3 KB

In [10]:
df.nunique()

price            1741
bedrooms           10
bathrooms          26
sqft_living       566
sqft_lot         3113
floors              6
waterfront          2
view                5
condition           5
sqft_above        511
sqft_basement     207
yr_built          115
yr_renovated       60
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='str':
        if df[col].nunique()<5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
             df[col]=encoder.fit_transform(df[col])

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
dtypes: float64(4), int64(9)
memory usage: 467.3 KB

# Scaling

In [13]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [15]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('price')

In [16]:
num_col

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated'],
      dtype='str')

In [17]:
df[num_col]=scaler.fit_transform(df[num_col])

In [18]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,0.333333,0.18750,0.073652,0.006775,0.2,0.0,0.0,0.50,0.107301,0.000000,0.482456,0.995531
1,2384000.0,0.555556,0.31250,0.249051,0.007835,0.4,0.0,1.0,1.00,0.331858,0.058091,0.184211,0.000000
2,342000.0,0.333333,0.25000,0.118451,0.010534,0.0,0.0,0.0,0.75,0.172566,0.000000,0.578947,0.000000
3,420000.0,0.333333,0.28125,0.123766,0.006885,0.0,0.0,0.0,0.75,0.069690,0.207469,0.552632,0.000000
4,550000.0,0.444444,0.31250,0.119210,0.009186,0.0,0.0,0.0,0.75,0.085177,0.165975,0.666667,0.989076

# Model Selection

In [19]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [20]:
lr

LinearRegression()

# Training

In [21]:
x=df.drop('price',axis=1)

In [22]:
y=df['price']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
lr.fit(x_train,y_train)

LinearRegression()

# Prediction

In [26]:
y_pred=lr.predict(x_test)

In [27]:
# y_pred[0]
y_pred

array([ 304863.38578065,  326517.0699151 , 1071762.53630093,
        546241.40097353,  379799.98321085,  605792.93622745,
        481263.57120648,  418905.11058134,  509341.50791918,
        530852.97588253,  682958.97641212,  414525.36130053,
        836974.40259898,  416500.85730815,  367263.4338822 ,
        702908.51672189,  677878.69067825,  515539.32998879,
       1019380.63891384,  861119.79490708, 1364866.21814691,
        637439.7001677 ,  634739.56666331,  470424.21250262,
        162037.15383035,  232831.37648238,  669951.05071599,
        884080.66694997,  263027.225772  ,  974954.6422947 ,
       1883342.16391314,  481510.29664856, 1275554.65253717,
        430994.93178865,  180366.40705418,  339240.1735742 ,
        792335.74094013, 1011053.14613385,  238036.20927671,
        543438.66040776,  423414.50597293,  243429.92107968,
        390151.30074032,  361322.67375673,  320343.34636012,
        317865.29287641,  469559.6064662 ,  573249.20158969,
        828966.75691609,  455286.46524115, 1213320.90955253,
        379278.14711424,  456992.2226116 ,  640657.0481953 ,
        281556.43960245,  355542.07843759,  977771.43585338,
        763946.83314539, 1012025.83150047,  286955.28768723,
        555835.6197761 ,  928556.49045173,  231280.25911122,
        910032.99943185,  769535.5723815 ,  562525.1115253 ,
        637463.19873752,  570860.06751281,  345837.01064878,
        295419.81242353, 1006508.17902271,  402155.24325432,
        367461.91266222,  870934.0557267 ,  349348.42679599,
        763750.32849305,  540526.04457529,  766712.74407835,
        477684.93612126,  229401.15552787,  563785.76349417,
        309224.69194754,  523372.99736614,  826306.84346142,
        359320.20890575,  272129.52465171,  384417.05303369,
        546211.65031837,  903097.91201908,  320858.51775887,
        845866.14311464,  285079.54355476,  304814.59399444,
        467565.73525597,  650291.30744731, 1143004.88154417,
        724309.9030022 ,  709038.64541315,  453017.90997356,
        476379.49824256,  501727.98469163,  380642.13128009,
        240381.51165495,  461838.2285364 ,  481557.05182964,
        948783.75966229,  660133.04579793,  290276.92365824,
        661221.23213652,  583725.99937399,  602486.70354449,
        575596.86113853,  294563.77075795,  388805.64120459,
        995324.89932127,  538263.87912047,  523482.02345962,
        679531.93989521,  468848.01606415,  355998.00959172,
        713098.11614058,  620513.40146268,  734301.37951915,
        419909.42644284,  261870.25647555,  309599.66817937,
        856156.9675605 ,  462619.44780867,  316249.45792284,
        619234.91457489,  410096.51028037,  421977.58123594,
        740906.84546302,  368934.95325237,  275512.1736878 ,
        339244.67408891,  326790.340907  ,  311169.82497175,
        607281.77186497,  724274.31637015,  358795.31130748,
        438734.57557099,  534109.63529711,  347968.72983403,
        962847.15890299,  843264.6972411 ,  247961.87220169,
        308624.05587789,  264645.83681693,  295180.66112287,
        403004.7028015 ,  715896.00537889,  709231.24879238,
        292807.56878766,  762270.71401049,  643055.17920432,
       1258126.75340614,  752499.84100328,  401925.78179461,
        251971.9566032 ,  359391.79025336,  940276.60823405,
        382562.36382344,  615368.51381235,  515703.35748948,
        594174.0227464 ,  842382.44396644,  308053.10540565,
        621516.05939245,  735550.62370109,  205470.86500575,
        466628.87635708,  873755.61292321,  347428.2670987 ,
        687181.77023252,  817197.54329572,  295237.22961943,
        663079.56797465,  669745.66313061,  334933.90721237,
        445168.97222078,  212192.27957851,  710770.66945562,
        385172.09260558,  380602.41200778, 1671266.35557845,
        693829.18041386,  340391.76908041,  630592.15427269,
        427606.62802458,  860962.99567347,  234677.28552324,
        236298.55856076,  647974.51481865,  513595.81813459,
       1495235.91491004,  795716.01922655,  970101.04401523,
        236515.87861698,  205976.17915483,  328649.24557336,
        599767.98478187,  161623.58859486,  591869.28189171,
        464183.13480309,  513400.24004991,  626164.24935867,
        538041.36304026,  331152.31562669,  816335.5078747 ,
        593225.64834892,  389452.46780561,  880687.09269029,
        480694.10881638,  557372.68907542,  377656.62793019,
        281998.24237933,  349371.21341272,  422950.87816742,
        353938.22060081,  710692.54097458,  659093.12027746,
        254629.33523894,  555123.39443171,  688125.60298321,
        547676.41950935,  363317.10585672,  334273.88910199,
        548334.22184755,  712203.51998898,  248058.76456352,
        354194.65822137,  296171.39441826,  451205.47091798,
        648109.36650123,  709124.98888429, 1289448.47850973,
        290094.31038033,  285637.30762796,  353669.55744401,
        544639.5279426 ,  504083.08204835,  565911.78776146,
        313289.58680413,  254998.67844759,  570794.91092593,
        482032.66178423,  551030.571717  ,  371889.15542464,
        382199.67711407,  243282.83298872,  130162.34899389,
        450633.5059817 ,  372246.93314193,  342553.26291117,
       1318129.04511749,  208538.80148272,  793719.75475545,
        581609.08164072,  358389.67813805,  162309.76012087,
        494467.57587948,  344484.48489267,  311498.37997762,
        506684.53189406,  572658.62918427,  726223.66978094,
        364395.07224358,  386904.65865814,  254419.20836787,
       1109090.23790865,  719615.28030939,  260734.38055073,
        879122.19827602,  394814.78468761,  287963.16250527,
        330188.20070809,  580943.65958484,  855375.07131318,
        313714.65770234,  394928.79591024,  395230.54460013,
        537149.03037451,  739095.6098922 ,  458637.48726431,
        302156.40348369,  780449.53768571,  551108.99056442,
       1102977.66959423,  247782.68424584,  254673.9234633 ,
        529500.28656744,  441877.37621312,  719485.84905121,
        364373.17509019,  571174.15928875,  853680.36800744,
        689587.79264256,  314072.87487036,  512657.5781769 ,
        365129.720298  ,  750378.49400222,  471570.81639343,
        587779.09592329,  576120.83232982,  585924.79061451,
        193553.31729768,  282802.82264515,  452779.8650541 ,
        594246.25503797, 3747679.54681719, 1637256.81672979,
       1156970.48270145, 1012440.67347612,  465966.6412534 ,
       1063456.65680832,  253833.22993087,  465355.94092571,
        916081.52451186,  378552.23503901,  563455.81196687,
        274346.4573011 ,  471101.25387305,  743148.40653091,
        437856.52021335,  366734.60225414,  288176.10983704,
        360667.87566613,  676203.79765277,  443257.30987712,
        291244.43600939,  643934.12121542,  356597.40770633,
        497350.94439295, 1000109.24014778,  173446.9348702 ,
        463991.43529468,  719851.84366774,  419864.56440113,
       1322674.18477491,  367171.0365365 ,  326407.98054277,
        327025.44358705,  574144.59642676,  864845.0684328 ,
        299733.9386136 ,  522813.83667118,  838827.5410937 ,
        424913.60827543,  270486.46786432,  601666.39623308,
        246626.78562439, 1149590.80227547,  375392.61177257,
        393153.22563147,  186187.20591473,  384061.37066552,
        614443.50208845,  461418.19362061,  657215.10929109,
        586644.12171005,  454716.25405969, 1191021.354051  ,
        331948.33304545,  557095.53793673,  808895.11216739,
        723692.68778767,  657688.13353304,  486897.57813316,
        292008.02496061,  459382.5955671 ,  619888.02588226,
        442195.08900132,  317122.36641295,  555183.78623134,
        561550.11563752,  251622.13946966,  760500.71657373,
        423722.54383684,  501938.09602326,  454082.7986895 ,
        302931.17096725,  258240.28348367,  542860.05300278,
        210332.74789807,  610756.40027404,  403275.82341809,
        942460.67673433,  415271.99064697,  347858.20683409,
        274980.64283846,  377943.79292612,  250048.03213685,
        640028.59543266,  157075.20406854,  849682.33005245,
        519103.58432849,  595184.22199731,  487084.6391556 ,
        464384.74985923,  339817.78031651,  251070.94564407,
       1059006.33313242,  701917.80480684,  872187.48323679,
        390399.38512143,  885843.88514453,  592752.96795513,
        341408.7490508 ,  601939.54146386,  496161.61052756,
        943525.70816041,  367671.44360277,  639713.66557804,
        536447.13293785,  563785.76349417,  260548.32023564,
        839482.02560386,  427088.28242492,  371895.31856828,
        536735.95696345,  231820.42689828,  463428.77640915,
        595640.39146902,  655048.21685931,  482140.45403887,
        720001.39109081,  432373.52242795,  209601.7131422 ,
        217535.89123733,  247114.74220663,  659189.27343378,
        510359.40600169,  395408.14138158,  501814.4195095 ,
        474163.98597888,  525377.50228386,  197801.93927663,
        195248.53514871,  591958.34203995,  740908.24338143,
        282767.41384529,  211823.8381455 ,  391762.307045  ,
        227033.43526083,  279113.32962319,  197157.96756663,
        647834.30994705, 1078736.16693825, 1124705.06726563,
        607665.526846  ,  851471.06460981,  751128.93783346,
        228370.75656863,  523876.23479938,  605968.1067143 ,
        380344.14038718,  686998.7784109 ,  686740.81454997,
        644735.12657214,  283788.42110733,  494782.31740254,
        305715.525261  ,  631258.59508783,  286327.39219018,
       1399339.33495246,  287934.50778438, 1181722.0177063 ,
        482445.99243697, 1219255.61502798,  196012.44451799,
        782289.61719243,  364224.05318786,  270208.20855716,
        365058.35316165,  619484.75777249,  650611.74396913,
       1350829.47252244,  375964.11285464,  498764.33812173,
        385647.04549287, 1073533.75667759,  695307.72541523,
        699163.81065102,  412315.51777994,  515599.06328151,
        705674.44705645,  224159.83840033,  271908.28307514,
        369571.93930203,  595511.19347979,  385351.24662641,
        663905.42188694,  244908.11791613,  328880.96337341,
        183321.67566968,  722011.39335944,  578489.60575107,
        487853.52317456,  425144.15791348,  669800.71470678,
        377376.57927232,  326039.02948355,  227931.41250224,
        468966.96201673,  737178.21852629,  382908.13514469,
        421452.40136273,  455173.37253164,  280856.8486457 ,
        322803.38329766,  619440.34383019, 1107208.48055661,
        820744.96209309,  565768.29278418,  598069.80771133,
        422687.90365996,  376198.2411126 ,  454250.15715724,
        707158.83528153,  349503.19206454,  499190.71044372,
        247203.44497322,  307664.50570907,  546731.17260189,
        261303.8752131 ,  852754.41319638,  188024.4174589 ,
        166007.01266941,  344981.27950146,  324142.33681464,
        617064.36388173,  296989.5800143 ,  883215.871448  ,
        502834.28849104,  516437.18671866,  413915.76660067,
        828985.14801775,  542311.5927542 ,  211889.11865777,
        521709.45327636,  377786.83526188,  185313.66453018,
        442272.74877086,  230129.22956995,  637630.80945176,
        316412.36182826,  737837.7723415 ,  400185.20740411,
        787277.27746293,  301076.50114967,  426083.13018163,
        680328.57409714,  459497.35241737,  257477.80806657,
        567695.09624891,  345116.48310144,  655437.74907023,
        408280.07772407,  412595.62049526,  411979.90858846,
        351688.06418121,  331277.76218933,  566054.186846  ,
        234632.20318682,  302875.0081869 , 1119428.80941993,
        698512.2713704 , 1993475.76057338,  407263.1150942 ,
        673035.62345768,  453782.23608865,  742215.65731269,
        636083.30377527,  247035.67311502,  586247.28280147,
        686364.05476276,  870113.76565049,  734178.10569869,
        152280.93158773,  275319.36900447,  170756.15040167,
        510259.96603915, 1170826.09125804,  520995.51208304,
        375058.51151161,  598509.47348762,  485027.51532337,
       1403645.47893075,  329564.50636235,  399175.43664428,
       1363505.56189644,  248513.01732478,  217990.94513323,
        572958.57971696,  632046.84570384,  446844.60744183,
        207164.54527016,  657332.20091619,  540277.97031731,
        408359.1917381 ,  237196.33315549,  246311.03669685,
        337762.06474793,  476406.69721464,  111892.43957044,
        616205.98030158,  783059.80656613,  741518.17225643,
        581235.58878199,  147165.15172831,  833868.20373634,
        252488.88520815,  608341.1750282 ,  752950.2429792 ,
        670980.11933514,  414935.59045337,  769396.20666379,
        659035.60129095, 1036037.28905241,  343547.28706974,
        662924.1423113 , 1124894.75877449,  578427.59320644,
        581325.53446141,  371478.24742393,  462867.58720099,
        927036.00272485, 1029377.72377993,  621419.64593561,
        508290.58493156,  199636.0610828 ,  574136.89802067,
        723026.19745094,  630493.45353115,  466079.14618314,
        292846.01722576,  216433.18296245,  505298.49197981,
        705110.26595256,  759661.28701508,  292604.1566984 ,
        532733.94822793,  830041.94300536,  228557.45036845,
        282274.33048447,  530715.37580349,  522246.81152082,
       1259473.12632741,  575401.65476279,  251800.09481382,
        521708.46409748,  365554.91847647,  559232.14098427,
       1009468.02423322, 1018713.38089421,  302358.62782873,
        226740.07061444,  811408.81880646,  205034.45022672,
        552251.99666768,  450440.23413973,  254571.06512046,
        623372.2179451 ,  427167.83917255,  672649.54728199,
        436908.0795107 ,  383810.94914879,  587737.362615  ,
        481917.83620937,  564368.76706422,  809845.24131524,
        403347.60829371, 1007160.86634251,  871843.37304354,
        442808.65832644,  896592.95932304,  952415.03154798,
        373549.12635199,  492945.04062966,  628450.49126519,
        458602.13956397,  356838.91588732,  509086.21139676,
        540767.27360064,  219302.95494359,  347809.98212796,
        272430.34180466,  437593.3448249 ,  777175.23249557,
        589499.03455778, 1094978.54029026,  569596.58083941,
        713306.19330197,  573586.56484185,  255701.56701579,
        513874.51083601,  264901.72924134,  204029.1824828 ,
        551974.63545391,  762792.64177452, 1069710.75245999,
        391012.10326701,  785447.22518777,  930912.33055815,
        669289.76822296,  526907.22933064,  288643.23577351,
        482018.81225699,  631706.18485555, 1348334.5140537 ,
        417903.59354916,  403955.5669589 ,  227709.35737838,
        279148.68383132,  411782.25390658,  209265.95028704,
        481603.36967418,  526775.50167821,  409952.73235535,
        439374.76789918,  731361.96941405,  684082.47745404,
       1172875.89432594,  273366.4981955 ,  428810.57813969,
        214372.73112983,  453033.4830678 ,  314216.4211438 ,
        420374.03169881,  723958.12673507,  822837.28415967,
        731468.3685189 ,  609406.64696115,  611793.62488987,
        688733.27429983,  681762.18778137, 1065349.20308032,
        297103.86193502,  332247.12526384,  745500.00331312,
        390927.57834857,  564742.29195173,  497650.3368851 ,
        439224.28290042,  398245.13435285,  458158.74008711,
        449872.16725987,  451512.13624373,  317880.6426594 ,
        189527.55130752,  523752.34745441,  730907.1971339 ,
        438402.63186132,  405697.55438103,  440466.89990895,
        614293.96768506,  500312.13216876,  212278.3119611 ,
        552883.87990064,  505993.57831118, 1090940.49167562,
        590481.29207514,  811916.69471943,  732082.51068666,
        422220.86449556,  381450.02626046,  495726.99591289,
        300586.0276909 ,  731207.25912413,  323105.24199386,
        206557.53757119,  522373.40014484,  423157.22820234,
        607631.06889812,  565341.41966378,  239878.30618136,
        395192.19208281, 1014385.7909589 ,  458064.15375102,
        286420.01056183,  707353.158747  ,  770590.41636111,
        346452.82366162,  407177.93996288,  438622.4170473 ,
        326124.69645471,  493028.74608395,  742347.39120421,
        208569.52019585,  603189.05322255,  407490.15341506,
        548954.27809988,  629929.58671671,  718038.54039645,
        422033.88099447,  559142.59869431,  939694.24046503,
        436509.453124  ,  416091.24987755,  493859.67986317,
        452502.96341007,  511344.48186187,  502954.30074426,
        189919.1186907 , 1049783.56521349,  429429.51240614,
       1073083.64634379,  549354.19381638,  685795.32141662,
        438452.32326622,  300327.24977438,  306503.96568309,
        494572.38644201,  614943.88943391,  632946.43077651,
        466775.63646364,  327839.87606078,  540604.40806972,
        253640.62359128,  605881.41221693,  543573.5864924 ,
        372413.31101363,  626564.46219489,  695932.91905713,
        481487.14080824,  623348.58302439,  418005.10061228,
        486333.74660187,  403250.65944125,  551683.32157232,
        470596.6090045 ,  409705.47933995,  487171.27666004,
        429399.82354228,  795663.57590403,  374614.85483606,
        242723.18025054,  526581.84200927,  895632.59905961,
        721051.36373872,  183051.2480018 ,  317383.44189464,
        434292.1517285 ,  202260.08221348,  482438.47805345,
       1438549.6851981 ,  387557.39871494,  272302.35815224,
        367149.26449779,  746281.50899959,  294578.95302346,
        749374.76454809,  571109.00346621, 1027484.81513772,
        688892.9490877 ,  257603.94595989,  410116.18009738,
        763952.4580923 ,  786118.55893842,  437893.46845427,
        448894.43105809,  804849.87659637,  298325.17123471,
        744258.66769595,  702156.7028807 ,  407295.81456181,
        770061.56305942,  517327.12820044,  489944.87863219,
        537898.7550461 ,  629907.13303493,  493438.2728113 ,
       1005476.07230224, 1172173.17170566,  818304.01046911,
        437167.20455056,  560987.64865338, 1817981.50124353,
        567263.71967373, 1400693.71486604,  942608.05094311,
        693081.86931315,  658655.30098248,  215440.2510278 ,
        387105.64373945,  380651.24542514,  356214.48396371,
        386769.36098994,  239522.60677348,  840218.51101298,
        231860.95819453,  605757.48664879,  755726.61119953,
        428056.7409143 ,  471230.69752611,  434741.68613768,
        693878.47489352,  468624.55671959,  145438.01384813,
        691853.23131626,  300997.05757005,  347219.69148189,
        380242.76377125,  306188.05833556,  620037.49492272,
        204081.1170355 ,  337110.09771374,  539724.99797517,
        515774.23716578,  524134.14632039,  645273.58209337,
        172108.58086372,  507750.25915008,  410029.16268314,
        443131.18231227,  441322.09004179,  204405.45392694,
        659612.42309007,  545264.71316848])

# Evaluation

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [29]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [30]:
print('mae',mae)
print('mse',mse)
print('r2',r2)

mae 210908.17325011524
mse 986921767056.1313
r2 0.03228385663277078