# Regression uchun

In [274]:
import pandas as pd
df=pd.read_csv("remote_work_productivity_regression.csv")

In [275]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      9700 non-null   float64
 1   Gender                   9706 non-null   str
 2   Country                  9709 non-null   str
 3   Experience_Years         9714 non-null   float64
 4   Work_Hours_Per_Day       9713 non-null   float64
 5   Remote_Work_Days         9675 non-null   float64
 6   Sleep_Hours              9717 non-null   float64
 7   Physical_Activity_Hours  9711 non-null   float64
 8   Meetings_Per_Day         9710 non-null   float64
 9   Screen_Time_Hours        9717 non-null   float64
 10  Internet_Speed_Mbps      9666 non-null   float64
 11  Stress_Level             9706 non-null   float64
 12  Job_Satisfaction         9689 non-null   float64
 13  Work_Life_Balance        9687 non-null   float64
 14  Productivity_Score       10000 non-null  float64
dtypes: float64(13), str(2)
memory usage: 1.1 MB

In [276]:
df.head()

,Age,Gender,Country,Experience_Years,Work_Hours_Per_Day,Remote_Work_Days,Sleep_Hours,Physical_Activity_Hours,Meetings_Per_Day,Screen_Time_Hours,Internet_Speed_Mbps,Stress_Level,Job_Satisfaction,Work_Life_Balance,Productivity_Score
0,48.0,Female,NaN,5.0,7.459628,0.0,4.700127,4.231575,5.0,8.814756,104.341825,6.0,0.582435,0.612683,53.258290
1,23.0,Female,Brazil,NaN,7.668602,3.0,9.500000,2.240209,4.0,10.764337,176.690218,3.0,0.442451,0.807667,64.288456
2,29.0,Male,India,3.0,9.847965,6.0,9.066660,2.392069,2.0,4.079460,184.258123,2.0,0.733397,0.705537,77.756502
3,48.0,Female,France,9.0,6.216410,6.0,8.076594,1.589339,6.0,10.167619,NaN,1.0,0.667250,0.834656,76.820529
4,24.0,Female,Canada,7.0,7.785025,1.0,6.608653,1.685547,2.0,10.011385,238.092071,1.0,0.981255,NaN,97.256139

In [277]:
df.tail()

,Age,Gender,Country,Experience_Years,Work_Hours_Per_Day,Remote_Work_Days,Sleep_Hours,Physical_Activity_Hours,Meetings_Per_Day,Screen_Time_Hours,Internet_Speed_Mbps,Stress_Level,Job_Satisfaction,Work_Life_Balance,Productivity_Score
9995,54.0,Male,India,9.0,9.414581,5.0,8.110255,0.945083,3.0,NaN,138.026250,5.0,0.756819,0.736245,72.152335
9996,47.0,Male,Spain,8.0,6.280649,6.0,7.425694,0.577085,1.0,11.793109,133.299152,10.0,0.547290,0.549004,52.898285
9997,43.0,Female,Germany,20.0,7.819181,0.0,8.711232,1.964948,3.0,5.070842,116.939226,10.0,NaN,0.886934,100.000000
9998,21.0,Male,UK,14.0,6.599259,2.0,6.363115,1.864498,2.0,9.300597,216.716502,1.0,0.440923,0.749200,95.388355
9999,54.0,NaN,UK,21.0,8.062015,3.0,8.175690,1.701992,4.0,9.396702,256.530601,5.0,0.803360,0.742639,100.000000

In [278]:
# Missing value
df.isna().sum()

Age                        300
Gender                     294
Country                    291
Experience_Years           286
Work_Hours_Per_Day         287
Remote_Work_Days           325
Sleep_Hours                283
Physical_Activity_Hours    289
Meetings_Per_Day           290
Screen_Time_Hours          283
Internet_Speed_Mbps        334
Stress_Level               294
Job_Satisfaction           311
Work_Life_Balance          313
Productivity_Score           0
dtype: int64

In [279]:
def fulla(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=="str":
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df
df=fulla(df)

In [280]:
df.isna().any()

Age                        False
Gender                     False
Country                    False
Experience_Years           False
Work_Hours_Per_Day         False
Remote_Work_Days           False
Sleep_Hours                False
Physical_Activity_Hours    False
Meetings_Per_Day           False
Screen_Time_Hours          False
Internet_Speed_Mbps        False
Stress_Level               False
Job_Satisfaction           False
Work_Life_Balance          False
Productivity_Score         False
dtype: bool

In [281]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      10000 non-null  float64
 1   Gender                   10000 non-null  str
 2   Country                  10000 non-null  str
 3   Experience_Years         10000 non-null  float64
 4   Work_Hours_Per_Day       10000 non-null  float64
 5   Remote_Work_Days         10000 non-null  float64
 6   Sleep_Hours              10000 non-null  float64
 7   Physical_Activity_Hours  10000 non-null  float64
 8   Meetings_Per_Day         10000 non-null  float64
 9   Screen_Time_Hours        10000 non-null  float64
 10  Internet_Speed_Mbps      10000 non-null  float64
 11  Stress_Level             10000 non-null  float64
 12  Job_Satisfaction         10000 non-null  float64
 13  Work_Life_Balance        10000 non-null  float64
 14  Productivity_Score       10000 non-null  float64
dtypes: float64(13), str(2)
memory usage: 1.1 MB

In [282]:
# Encoding jarayoni
from sklearn.preprocessing import LabelEncoder

In [283]:
df.nunique()

Age                          41
Gender                        2
Country                      12
Experience_Years             26
Work_Hours_Per_Day         9707
Remote_Work_Days              8
Sleep_Hours                9680
Physical_Activity_Hours    9642
Meetings_Per_Day              9
Screen_Time_Hours          9695
Internet_Speed_Mbps        9407
Stress_Level                 11
Job_Satisfaction           9464
Work_Life_Balance          9456
Productivity_Score         7275
dtype: int64

In [284]:
def raqamla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=="str":
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [285]:
df=raqamla(df)

In [286]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      10000 non-null  float64
 1   Country                  10000 non-null  int64
 2   Experience_Years         10000 non-null  float64
 3   Work_Hours_Per_Day       10000 non-null  float64
 4   Remote_Work_Days         10000 non-null  float64
 5   Sleep_Hours              10000 non-null  float64
 6   Physical_Activity_Hours  10000 non-null  float64
 7   Meetings_Per_Day         10000 non-null  float64
 8   Screen_Time_Hours        10000 non-null  float64
 9   Internet_Speed_Mbps      10000 non-null  float64
 10  Stress_Level             10000 non-null  float64
 11  Job_Satisfaction         10000 non-null  float64
 12  Work_Life_Balance        10000 non-null  float64
 13  Productivity_Score       10000 non-null  float64
 14  Gender_Female            10000 non-null  int64
 15  Gender_Male              10000 non-null  int64
dtypes: float64(13), int64(3)
memory usage: 1.2 MB

In [287]:
df.head()

,Age,Country,Experience_Years,Work_Hours_Per_Day,Remote_Work_Days,Sleep_Hours,Physical_Activity_Hours,Meetings_Per_Day,Screen_Time_Hours,Internet_Speed_Mbps,Stress_Level,Job_Satisfaction,Work_Life_Balance,Productivity_Score,Gender_Female,Gender_Male
0,48.0,4,5.000000,7.459628,0.0,4.700127,4.231575,5.0,8.814756,104.341825,6.0,0.582435,0.612683,53.258290,1,0
1,23.0,0,11.977352,7.668602,3.0,9.500000,2.240209,4.0,10.764337,176.690218,3.0,0.442451,0.807667,64.288456,1,0
2,29.0,4,3.000000,9.847965,6.0,9.066660,2.392069,2.0,4.079460,184.258123,2.0,0.733397,0.705537,77.756502,0,1
3,48.0,2,9.000000,6.216410,6.0,8.076594,1.589339,6.0,10.167619,140.172597,1.0,0.667250,0.834656,76.820529,1,0
4,24.0,1,7.000000,7.785025,1.0,6.608653,1.685547,2.0,10.011385,238.092071,1.0,0.981255,0.700173,97.256139,1,0

In [288]:
# Scaling jarayoni
from sklearn.preprocessing import MinMaxScaler

In [289]:
def ritimla(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=["float64","int64"]).columns.drop("Productivity_Score")
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [290]:
df=ritimla(df)

In [291]:
df.head()

,Age,Country,Experience_Years,Work_Hours_Per_Day,Remote_Work_Days,Sleep_Hours,Physical_Activity_Hours,Meetings_Per_Day,Screen_Time_Hours,Internet_Speed_Mbps,Stress_Level,Job_Satisfaction,Work_Life_Balance,Productivity_Score,Gender_Female,Gender_Male
0,0.717949,0.363636,0.208333,0.432453,0.000000,0.127296,0.669648,0.714286,0.528614,0.243224,0.555556,0.537216,0.542201,53.258290,1.0,0.0
1,0.076923,0.000000,0.499056,0.458575,0.500000,1.000000,0.354514,0.571429,0.705849,0.420359,0.222222,0.382073,0.772667,64.288456,1.0,0.0
2,0.230769,0.363636,0.125000,0.730996,1.000000,0.921211,0.378546,0.285714,0.098133,0.438887,0.111111,0.704526,0.651953,77.756502,0.0,1.0
3,0.717949,0.181818,0.375000,0.277051,1.000000,0.741199,0.251513,0.857143,0.651602,0.330950,0.000000,0.631216,0.804568,76.820529,1.0,0.0
4,0.102564,0.090909,0.291667,0.473128,0.166667,0.474300,0.266738,0.285714,0.637399,0.570692,0.000000,0.979226,0.645612,97.256139,1.0,0.0

In [292]:
# Target(output) va Feature(input) ga ajratish
from sklearn.model_selection import train_test_split

In [293]:
x=df.drop("Productivity_Score",axis=1).astype(int)
y=df["Productivity_Score"].astype(int)

In [294]:
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# `Algorithm(model) tanlash`

# Linear Regression

In [295]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [296]:
lr

LinearRegression()

In [297]:
# Fitting(algorithmni o'qitish)
lr.fit(x_train,y_train)

LinearRegression()

In [298]:
# Predict(baxolash)
y_pred=lr.predict(x_test)

In [299]:
# Evaluation
from sklearn.metrics import r2_score, mean_absolute_error

In [300]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [301]:
print(f'r2: {r2}')
print("mae: ", mae)

r2: 0.0607636755738058
mae:  13.880704336133114

# `K-Fold` -> Linear Regression

In [302]:
from sklearn.model_selection import KFold, cross_val_score

In [303]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [304]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [305]:
scores=cross_val_score(lr,x,y,cv=kf,scoring='r2')

In [306]:
print(scores)

[0.06076368 0.06652646 0.06438539 0.07594443 0.06887962]

In [307]:
for i in scores:
    print(i)

0.0607636755738058
0.06652645794852019
0.06438539388006248
0.07594443106540705
0.06887961924816322

In [308]:
import numpy as np

In [309]:
np.mean(scores)

np.float64(0.06729991554319174)

In [310]:
np.std(scores)

np.float64(0.005080122410381962)

In [311]:
# mean_absolute_errorni topish
from sklearn.metrics import make_scorer

In [312]:
mae=make_scorer(mean_absolute_error,greater_is_better=False)

In [313]:
score=cross_val_score(lr,x,y,cv=kf,scoring=mae)

In [314]:
print(-score)
print(-score.mean())

[13.88070434 13.55554104 13.54692136 13.53578004 13.74075192]
13.65193974026757

In [315]:
for i in score:
    print(-i)

13.880704336133109
13.555541038633498
13.546921358951046
13.535780042799761
13.740751924820438

# Decition Tree Regressor

In [316]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()

In [317]:
dtr

DecisionTreeRegressor()

In [318]:
# Fitting
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [319]:
# Predict
y_pred=dtr.predict(x_test)

In [320]:
# Evaluation
from sklearn.metrics import r2_score, mean_absolute_error

In [321]:
r2_dtr=r2_score(y_test,y_pred)
mae_dtr=mean_absolute_error(y_test,y_pred)

In [322]:
print(f'dtr_r2: {r2_dtr}')
print("dtr_mae: ", mae_dtr)

dtr_r2: 0.0593247307279372
dtr_mae:  13.83753400030122

# `K-Fold` -> Decision Tree Regressor

In [323]:
from sklearn.model_selection import KFold, cross_val_score

In [324]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [325]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [326]:
scores_dtr=cross_val_score(dtr,x,y,cv=kf,scoring='r2')

In [327]:
print(scores_dtr)

[0.05932473 0.05378444 0.05844148 0.04546365 0.05987312]

In [328]:
for i in scores_dtr:
    print(i)

0.05932473072793709
0.0537844390770047
0.05844148033645136
0.045463653593170505
0.059873124881124284

In [329]:
import numpy as np

In [330]:
np.mean(scores_dtr)

np.float64(0.05537748572313759)

In [331]:
np.std(scores_dtr)

np.float64(0.005403729132276648)

In [332]:
# mean_absolute_errorni topish
from sklearn.metrics import make_scorer

In [333]:
mae=make_scorer(mean_absolute_error,greater_is_better=False)

In [334]:
score_dtr=cross_val_score(dtr,x,y,cv=kf,scoring=mae)

In [335]:
print(-score_dtr)

[13.837534   13.56409654 13.5474226  13.63040196 13.72043014]

In [336]:
for i in score_dtr:
    print(-i)

13.83753400030122
13.56409653551086
13.54742260254267
13.630401958965729
13.720430144495086

In [337]:
import numpy as np

In [338]:
np.mean(-score_dtr)

np.float64(13.659977048363112)

In [339]:
np.std(-score_dtr)

np.float64(0.10762649297000669)

# Random Forest Regressor

In [340]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()

In [341]:
rfr

RandomForestRegressor()

In [342]:
# Fitting
rfr.fit(x_train,y_train)

RandomForestRegressor()

In [343]:
# Predict
y_pred=rfr.predict(x_test)

In [344]:
# Evaluation
from sklearn.metrics import r2_score, mean_absolute_error

In [345]:
r2_rfr=r2_score(y_test,y_pred)
mae_rfr=mean_absolute_error(y_test,y_pred)

In [346]:
print(f'rfr_r2: {r2_rfr}')
print("rfr_mae: ", mae_rfr)

rfr_r2: 0.05971385138462171
rfr_mae:  13.837448753172458

# `K-Fold` -> Random Forest Regressor

In [347]:
from sklearn.model_selection import KFold, cross_val_score

In [348]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [349]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [350]:
scores_rfr=cross_val_score(rfr,x,y,cv=kf,scoring='r2')

In [351]:
print(scores_rfr)

[0.06029431 0.05971419 0.06113804 0.05068672 0.06297756]

In [352]:
for i in scores_rfr:
    print(i)

0.06029431398057328
0.05971419010653367
0.061138035377424904
0.050686724217489765
0.06297756284353528

In [353]:
import numpy as np

In [354]:
np.mean(scores_rfr)

np.float64(0.05896216530511138)

In [355]:
np.std(scores_rfr)

np.float64(0.004282076938901392)

In [356]:
# mean_absolute_errorni chiqarish
from sklearn.metrics import make_scorer

In [357]:
mae=make_scorer(mean_absolute_error,greater_is_better=False)

In [358]:
score_rfr=cross_val_score(rfr,x,y,cv=kf,scoring=mae)

In [359]:
print(-score_rfr)

[13.83342838 13.54402444 13.53073332 13.61690663 13.70846302]

In [360]:
for i in score_rfr:
    print(-i)

13.833428381060433
13.54402443717754
13.530733323193985
13.616906633843707
13.708463021391974

In [361]:
np.mean(-score_rfr)

np.float64(13.646711159333526)

In [362]:
np.std(score_rfr)

np.float64(0.11274781104706601)

# Support Vector Machine (Regressor)

In [363]:
from sklearn.svm import SVR
svr=SVR(kernel='linear',C=1.0)

In [364]:
svr

SVR(kernel='linear')

In [365]:
# Fitting
svr.fit(x_train,y_train)

SVR(kernel='linear')

In [366]:
# Predict
y_pred=svr.predict(x_test)

In [367]:
# Evaluation
from sklearn.metrics import r2_score, mean_absolute_error

In [368]:
r2_svr=r2_score(y_test,y_pred)
mae_svr=mean_absolute_error(y_test,y_pred)

In [369]:
print(f'svr_r2: {r2_svr}')
print("svr_mae: ", mae_svr)

svr_r2: 0.01671542395956427
svr_mae:  13.856024243978238

# `K-Fold` -> Support Vector Machine (Regressor)

In [370]:
from sklearn.model_selection import KFold, cross_val_score

In [371]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [372]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [373]:
scores_svr=cross_val_score(svr,x,y,cv=kf,scoring='r2')

In [374]:
print(scores_svr)

[0.01671587 0.03084432 0.05212443 0.05315902 0.0406596 ]

In [375]:
for i in scores_svr:
    print(i)

0.01671586812725101
0.030844322386899603
0.05212442891230862
0.053159022211821116
0.040659595382649405

In [376]:
import numpy as np

In [377]:
np.mean(scores_svr)

np.float64(0.03870064740418595)

In [378]:
np.std(scores_svr)

np.float64(0.013697681204284095)

In [379]:
# mean_absolute_errorni chiqarish
from sklearn.metrics import make_scorer

In [380]:
mae=make_scorer(mean_absolute_error,greater_is_better=False)

In [381]:
score_svr=cross_val_score(svr,x,y,cv=kf,scoring=mae)

In [382]:
print(-score_svr)

[13.85602832 13.48281785 13.24334653 13.37743725 13.60441645]

In [383]:
for i in score_svr:
    print(-i)

13.856028320286983
13.482817848874602
13.243346532058744
13.37743724891036
13.60441645324363

In [384]:
np.mean(-score_svr)

np.float64(13.512809280674864)

In [385]:
np.std(score_svr)

np.float64(0.2088187870262361)

# Tabulate

In [386]:
from tabulate import tabulate

In [387]:
results=[
    ["Linear Regression",0.0607,13.8807],
    ["Decision Tree Regressor",0.0593,13.8375],
    ["Random Forest Regressor",0.0603,13.8333],
    ["Support Vector Regressor",0.0167,13.8560]
]

In [388]:
headers = ["Model","r2_score","mae"]
table=tabulate(results,headers=headers,tablefmt="grid",floatfmt=".2f")

In [389]:
print(table)

+--------------------------+------------+-------+
| Model                    |   r2_score |   mae |
+==========================+============+=======+
| Linear Regression        |       0.06 | 13.88 |
+--------------------------+------------+-------+
| Decision Tree Regressor  |       0.06 | 13.84 |
+--------------------------+------------+-------+
| Random Forest Regressor  |       0.06 | 13.83 |
+--------------------------+------------+-------+
| Support Vector Regressor |       0.02 | 13.86 |
+--------------------------+------------+-------+