# 1-oylik Proyekt

In [102]:
import pandas as pd
df=pd.read_csv('autos.csv')

In [103]:
df.info()
# 0.index --> Qator raqami
# 1.DataCrawled --> Ma’lumot yig‘ilgan sana(Saytdan qachon yuklab olingan)
# 2.name -->  Mashina nomi
# 3.seller --> Sotuvchi turi
# 4.offerType --> Taklif turi(Angebot)
# 5.price --> Narx
# 6.abtest --> A/B test guruhi(test/control)
# 7.vehicleType --> Mashina turi
# 8.year0fRegistration --> Ro'yhatdan o'tgan yili
# 9.gearbox --> Uzatmalar qutisi(mexanik/avtomat)
# 10.powerPs --> Ot kuchi(Dvigatel quvvati(PS))
# 11.model --> Model
# 12.kilometer --> Yurgan masofasi
# 13.month0fRegistration --> 1-12oy oralig'i
# 14.fuelType --> Yoqilg'i turi
# 15.brand --> Markasi
# 16.notRepairedDamage --> Tuzatilmagan shikast(Nan/nein/ja-avariya bo'lganmi yoki yoq)
# 17.dateCreated --> E'lon(ma'lumot) yaratilgan sana
# 18.nr0fPictures --> Rasmlar soni
# 19.postalCode --> Pochta indeksi
# 20.lastSeen --> Oxirgi ko'rilgan sana

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  str
dtypes: int64(8), str(13)
memory usage: 59.5 MB

In [104]:
df.head()

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [105]:
df.tail()

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
371523,371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [106]:
df["price"].describe()

count    3.715280e+05
mean     1.729514e+04
std      3.587954e+06
min      0.000000e+00
25%      1.150000e+03
50%      2.950000e+03
75%      7.200000e+03
max      2.147484e+09
Name: price, dtype: float64

In [107]:
df = df[(df["price"]>100) & (df["price"]<50000)] # biz buni ishlatmagandik predict paytida target manfiy sonlar chiqdi

In [108]:
df.isnull().sum()

index                      0
dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            32561
yearOfRegistration         0
gearbox                16334
powerPS                    0
model                  17425
kilometer                  0
monthOfRegistration        0
fuelType               28360
brand                      0
notRepairedDamage      64652
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [109]:
df.drop(columns=['index','dateCrawled','name','offerType','abtest','nrOfPictures','lastSeen'],inplace=True)

In [110]:
df.info()

<class 'pandas.DataFrame'>
Index: 355594 entries, 0 to 371527
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   seller               355594 non-null  str
 1   price                355594 non-null  int64
 2   vehicleType          323033 non-null  str
 3   yearOfRegistration   355594 non-null  int64
 4   gearbox              339260 non-null  str
 5   powerPS              355594 non-null  int64
 6   model                338169 non-null  str
 7   kilometer            355594 non-null  int64
 8   monthOfRegistration  355594 non-null  int64
 9   fuelType             327234 non-null  str
 10  brand                355594 non-null  str
 11  notRepairedDamage    290942 non-null  str
 12  dateCreated          355594 non-null  str
 13  postalCode           355594 non-null  int64
dtypes: int64(6), str(8)
memory usage: 40.7 MB

# Preprocessing

In [111]:
df.isnull().any()

seller                 False
price                  False
vehicleType             True
yearOfRegistration     False
gearbox                 True
powerPS                False
model                   True
kilometer              False
monthOfRegistration    False
fuelType                True
brand                  False
notRepairedDamage       True
dateCreated            False
postalCode             False
dtype: bool

In [112]:
print(df.dtypes)

seller                   str
price                  int64
vehicleType              str
yearOfRegistration     int64
gearbox                  str
powerPS                int64
model                    str
kilometer              int64
monthOfRegistration    int64
fuelType                 str
brand                    str
notRepairedDamage        str
dateCreated              str
postalCode             int64
dtype: object

In [113]:
# missing + for loop

In [114]:
for col in df.columns:
    if df[col].isnull().sum():
        if df[col].dtype=="str":
            df[col] = df[col].fillna("Unknown")
            #df[col].fillna("Unknown")

In [115]:
#for col in df.columns:
#if df[col].isnull().sum():
#if df[col].dtype=="str":
#df[col] = df[col].fillna(df[col].mode()[0])

In [116]:
df.isnull().sum()

seller                 0
price                  0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
postalCode             0
dtype: int64

In [117]:
# encoding

In [118]:
df.nunique() #classlar soni

seller                    2
price                  4941
vehicleType               9
yearOfRegistration      140
gearbox                   3
powerPS                 742
model                   252
kilometer                13
monthOfRegistration      13
fuelType                  8
brand                    40
notRepairedDamage         3
dateCreated             113
postalCode             8145
dtype: int64

In [119]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [120]:
encoder

LabelEncoder()

In [121]:
# encoding + for loop
for col in df.columns:
    if df[col].dtype=="string":
        if df[col].nunique()<=3:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
        else:
            df[col] = encoder.fit_transform(df[col])

In [122]:
df.head()

,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,dateCreated,postalCode,seller_gewerblich,seller_privat,gearbox_Unknown,gearbox_automatik,gearbox_manuell,notRepairedDamage_Unknown,notRepairedDamage_ja,notRepairedDamage_nein
0,480,0,1993,0,119,150000,0,2,38,98,70435,0,1,0,0,1,1,0,0
1,18300,4,2011,190,26,125000,5,4,1,98,66954,0,1,0,0,1,0,1,0
2,9800,8,2004,163,120,125000,8,4,14,88,90480,0,1,0,1,0,1,0,0
3,1500,5,2001,75,119,150000,6,2,38,91,91074,0,1,0,0,1,0,0,1
4,3600,5,2008,69,104,90000,7,4,31,105,60437,0,1,0,0,1,0,0,1

In [123]:
df.info()

<class 'pandas.DataFrame'>
Index: 355594 entries, 0 to 371527
Data columns (total 19 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   price                      355594 non-null  int64
 1   vehicleType                355594 non-null  int64
 2   yearOfRegistration         355594 non-null  int64
 3   powerPS                    355594 non-null  int64
 4   model                      355594 non-null  int64
 5   kilometer                  355594 non-null  int64
 6   monthOfRegistration        355594 non-null  int64
 7   fuelType                   355594 non-null  int64
 8   brand                      355594 non-null  int64
 9   dateCreated                355594 non-null  int64
 10  postalCode                 355594 non-null  int64
 11  seller_gewerblich          355594 non-null  int64
 12  seller_privat              355594 non-null  int64
 13  gearbox_Unknown            355594 non-null  int64
 14  gearbox_automatik          355594 non-null  int64
 15  gearbox_manuell            355594 non-null  int64
 16  notRepairedDamage_Unknown  355594 non-null  int64
 17  notRepairedDamage_ja       355594 non-null  int64
 18  notRepairedDamage_nein     355594 non-null  int64
dtypes: int64(19)
memory usage: 54.3 MB

In [124]:
# Scaling

In [125]:
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler
scaler=MinMaxScaler()

In [126]:
scaler

MinMaxScaler()

In [127]:
num_cols=df.select_dtypes(include=["int64"]).columns.drop("price")

In [128]:
num_cols

Index(['vehicleType', 'yearOfRegistration', 'powerPS', 'model', 'kilometer',
       'monthOfRegistration', 'fuelType', 'brand', 'dateCreated', 'postalCode',
       'seller_gewerblich', 'seller_privat', 'gearbox_Unknown',
       'gearbox_automatik', 'gearbox_manuell', 'notRepairedDamage_Unknown',
       'notRepairedDamage_ja', 'notRepairedDamage_nein'],
      dtype='str')

In [129]:
df.head()

,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,dateCreated,postalCode,seller_gewerblich,seller_privat,gearbox_Unknown,gearbox_automatik,gearbox_manuell,notRepairedDamage_Unknown,notRepairedDamage_ja,notRepairedDamage_nein
0,480,0,1993,0,119,150000,0,2,38,98,70435,0,1,0,0,1,1,0,0
1,18300,4,2011,190,26,125000,5,4,1,98,66954,0,1,0,0,1,0,1,0
2,9800,8,2004,163,120,125000,8,4,14,88,90480,0,1,0,1,0,1,0,0
3,1500,5,2001,75,119,150000,6,2,38,91,91074,0,1,0,0,1,0,0,1
4,3600,5,2008,69,104,90000,7,4,31,105,60437,0,1,0,0,1,0,0,1

In [130]:
df[num_cols]=scaler.fit_transform(df[num_cols])

In [131]:
# Model selection

In [132]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [133]:
lr

LinearRegression()

In [134]:
# Input(x,feature) va Output(y,target) ajratib olish

In [135]:
# Input
x=df.drop("price",axis=1)

In [136]:
# Output
y=df["price"]

In [137]:
# Train/Test

In [138]:
from sklearn.model_selection import train_test_split

In [139]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [140]:
x_train.shape

(284475, 18)

In [141]:
y_train.shape

(284475,)

In [142]:
x_test.shape

(71119, 18)

In [143]:
y_test.shape

(71119,)

In [144]:
lr.fit(x_train,y_train)

LinearRegression()

In [145]:
# prediction(bashorat qilish)

In [146]:
y_predict=lr.predict(x_test)

In [147]:
y_predict

array([21960.22827071,  9160.44048877,  2282.40316991, ...,
        2017.93804935, 12307.2899152 ,  5252.7690543 ], shape=(71119,))

In [148]:
# Evaluation(bu modelning bashorati qanchalik to‘g‘ri ekanini tekshirish jarayoni)

In [149]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [150]:
mae=mean_absolute_error(y_test,y_predict) #Model o‘rtacha nechchi % xato qilganini ko‘rsatadi
mse=mean_squared_error(y_test,y_predict) #Model qilgan xatolarning o‘rtacha kvadratini topadi(manfiy yoqoladi,katta xatolar ko'proq jazolanadi)
r2=r2_score(y_test,y_predict) # 1ga yaqin → juda yaxshi, 0 → o'rtacha, 0dan kichik → juda yomon

In [152]:
print("mae: ",mae)
print("mse: ",mse)
print("r2: ",r2)

mae:  3461.8186893449356
mse:  27095019.47584071
r2:  0.39233408027751215