In [17]:
import pandas as pd

df = pd.read_csv("/Users/sherzodbeksharobiddinov/MLFoundation/Sherzod_dev/2-oy_Model_Building/Data/bank-full.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [ ]:
def fill_val(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype == 'object':
                df[col].fillna(df[col].mode()[0], inplace=True)
            else:
                df[col].fillna(df[col].mean(), inplace=True)
    return df

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
# labeling funksiyasi

def d_label(df):
    labelencoder = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == "object":
            if df[col].nunique()<=5:
                dummies = pd.get_dummies(df[col],prefix=col,dtype=int)
                df = pd.concat([df.drop(columns= col ),dummies],axis=1)
            else:
                df[col] = labelencoder.fit_transform(df[col])
    return df

In [24]:
d_label(df)

,age,job,balance,day,month,duration,campaign,pdays,previous,marital_divorced,...,loan_yes,contact_cellular,contact_telephone,contact_unknown,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,y_no,y_yes
0,58,4,2143,5,8,261,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
1,44,9,29,5,8,151,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
2,33,2,2,5,8,76,1,-1,0,0,...,1,0,0,1,0,0,0,1,1,0
3,47,1,1506,5,8,92,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
4,33,11,1,5,8,198,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,825,17,9,977,3,-1,0,0,...,0,1,0,0,0,0,0,1,0,1
45207,71,5,1729,17,9,456,2,-1,0,1,...,0,1,0,0,0,0,0,1,0,1
45208,72,5,5715,17,9,1127,5,184,3,0,...,0,1,0,0,0,0,1,0,0,1
45209,57,1,668,17,9,508,4,-1,0,0,...,0,0,1,0,0,0,0,1,1,0
45210,37,2,2971,17,9,361,2,188,11,0,...,0,1,0,0,0,1,0,0,1,0

In [32]:

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder
def ds_encoding(df):
    encoder = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == 'object':
            if df[col].nunique() <= 5:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df = pd.concat([df.drop(columns=col), dummies], axis=1)
            else: 
                df[col] = encoder.fit_transform(df[col])
    return df



df = ds_encoding(df)

In [35]:
num_col = df.select_dtypes(include=['int64', 'float64'])

In [36]:
num_col

,age,job,balance,day,month,duration,campaign,pdays,previous,marital_divorced,...,loan_yes,contact_cellular,contact_telephone,contact_unknown,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,y_no,y_yes
0,58,4,2143,5,8,261,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
1,44,9,29,5,8,151,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
2,33,2,2,5,8,76,1,-1,0,0,...,1,0,0,1,0,0,0,1,1,0
3,47,1,1506,5,8,92,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
4,33,11,1,5,8,198,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,825,17,9,977,3,-1,0,0,...,0,1,0,0,0,0,0,1,0,1
45207,71,5,1729,17,9,456,2,-1,0,1,...,0,1,0,0,0,0,0,1,0,1
45208,72,5,5715,17,9,1127,5,184,3,0,...,0,1,0,0,0,0,1,0,0,1
45209,57,1,668,17,9,508,4,-1,0,0,...,0,0,1,0,0,0,0,1,1,0
45210,37,2,2971,17,9,361,2,188,11,0,...,0,1,0,0,0,1,0,0,1,0

In [42]:
from sklearn.preprocessing import MinMaxScaler
# scaler funsksiyasi

def data_scaler(df,num_col):
    minmaxScler = MinMaxScaler()
    df[num_col] = minmaxScler.fit_transform(df[num_col])
    return df

num_col = df.select_dtypes(include=['int64', 'float64'])

In [43]:
data_scaler(df,num_col)

ValueError: Boolean array expected for the condition, not int64