In [14]:
import pandas as pd
df = pd.read_csv("C:/Users/PC/MLFoundation-main/Sherzod_dev/2-oy_Model_Building/Data/Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
def fill_val(df):
    for col in df.columns: # Barcha ustunlarni bittadan aylanib chiqamiz (Loop)
        if df[col].isnull().any(): # Agar shu ustunda aqalli 1 ta bo'sh qator bo'lsa:
            
            # Agar ustundagi ma'lumot tipi "Matn/So'z" (object) bo'lsa:
            if df[col].dtype == 'object': 
                # Bo'sh kataklarni eng ko'p takrorlangan so'z bilan (mode()[0]) to'ldiramiz
                df[col].fillna(df[col].mode()[0], inplace=True) 
            
            # Aks holda (ya'ni ma'lumot tipi raqam bo'lsa):
            else:
                # Bo'sh kataklarni barcha talabalar natijasining O'rtachasi (mean()) bilan to'ldiramiz
                df[col].fillna(df[col].mean(), inplace=True)
    return df # Tozalangan jadvalni qaytaramiz

# Yozgan funksiyamizni jadvalimiz(df) ga ishlatib yuboramiz
fill_val(df)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
from sklearn.preprocessing import LabelEncoder

def ds_encoding(df):
    encoder = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == 'object': # Faqat Matn qatnashgan ustunlarga qaraymiz
            
             # Agar u ustunda 5 ta dan kam variant bo'lsa (Masalan: Male, Female, Other = 3 ta)
            if df[col].nunique() <= 5:
                # Ularni alohida ustunlarga ajratib(One-Hot Encoding), ichini 0 yoki 1 qilib chiqadi
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                # Eskisini o'chirib, Yangi 0 va 1 lik ustunni asosiy jadvalga yopishtiramiz
                df = pd.concat([df.drop(columns=col), dummies], axis=1)
            
            # Agar ro'yxat katta bo'lsa (masalan 10 xil daraja bor bo'lsa):
            else: 
                # So'zlarni shunchaki 0, 1, ... 10 raqamlariga moslab o'zgartirib qoyadi (M: Apple=0, Banana=1)
                df[col] = encoder.fit_transform(df[col])
    return df

df = ds_encoding(df)

In [8]:
def salom_ber(name):
	print("Assalomu laykum " + name)

salom_ber("sherzod")

Assalomu laykum sherzod