In [19]:
import pandas as pd

df = pd.read_csv("/Users/sherzodbeksharobiddinov/MLFoundation/Sherzod_dev/2-oy_Model_Building/Data/bank-full.csv")
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [3]:
def fill_val(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype == 'object':
                df[col].fillna(df[col].mode()[0], inplace=True)
            else:
                df[col].fillna(df[col].mean(), inplace=True)
    return df

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
# labeling funksiyasi

def d_label(df):
    labelencoder = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == "object":
            if df[col].nunique()<=5:
                dummies = pd.get_dummies(df[col],prefix=col,dtype=int)
                df = pd.concat([df.drop(columns= col ),dummies],axis=1)
            else:
                df[col] = labelencoder.fit_transform(df[col])
    return df

In [6]:
d_label(df)

,age,job,balance,day,month,duration,campaign,pdays,previous,marital_divorced,...,loan_yes,contact_cellular,contact_telephone,contact_unknown,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,y_no,y_yes
0,58,4,2143,5,8,261,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
1,44,9,29,5,8,151,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
2,33,2,2,5,8,76,1,-1,0,0,...,1,0,0,1,0,0,0,1,1,0
3,47,1,1506,5,8,92,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
4,33,11,1,5,8,198,1,-1,0,0,...,0,0,0,1,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,825,17,9,977,3,-1,0,0,...,0,1,0,0,0,0,0,1,0,1
45207,71,5,1729,17,9,456,2,-1,0,1,...,0,1,0,0,0,0,0,1,0,1
45208,72,5,5715,17,9,1127,5,184,3,0,...,0,1,0,0,0,0,1,0,0,1
45209,57,1,668,17,9,508,4,-1,0,0,...,0,0,1,0,0,0,0,1,1,0
45210,37,2,2971,17,9,361,2,188,11,0,...,0,1,0,0,0,1,0,0,1,0

In [ ]:
# sklear kutubhonasi preprocessing modulidan LabelEncoder classini chaqiramiz
from sklearn.preprocessing import LabelEncoder
# klassdan nusha olamiz
encoder = LabelEncoder()
encoder
def ds_encoding(df):
    encoder = LabelEncoder()
    # col birma bir tekshirib chiqadi
    for col in df.columns:
        # dfni ichidan datatypesi object bolgandi ajratadi
        if df[col].dtype == 'object':
            # bir biriga oxshash Number of Unique qiymatlarni aniqledi
            if df[col].nunique() <= 5:
                # bitta ustundi bir necha ustunlarga ajratadi sharti 5 tadan kam bolishi kerak
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                # eskilarini concat yopishtrish xa drop ochirib tashlash 
                df = pd.concat([df.drop(columns=col), dummies], axis=1)
            else: 
                # ikkita amal bir vaqtda fit ahratadi transform ozgartradi 
                df[col] = encoder.fit_transform(df[col])
    return df



df = ds_encoding(df)

In [13]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns

In [14]:
num_col

Index(['age', 'job', 'balance', 'day', 'month', 'duration', 'campaign',
       'pdays', 'previous', 'marital_divorced', 'marital_married',
       'marital_single', 'education_primary', 'education_secondary',
       'education_tertiary', 'education_unknown', 'default_no', 'default_yes',
       'housing_no', 'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'poutcome_failure',
       'poutcome_other', 'poutcome_success', 'poutcome_unknown', 'y_no',
       'y_yes'],
      dtype='object')

In [15]:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler

MinMaxScaler()

In [20]:

# scaler funsksiyasi

def data_scaler(df,num_col):
    minmaxScler = MinMaxScaler()
    df[num_col] = minmaxScler.fit_transform(df[num_col])
    return df
num_col = df.select_dtypes(include=['int64', 'float64']).columns
data_scaler(df, num_col)

,age,job,balance,day,month,duration,campaign,pdays,previous,marital_divorced,...,loan_yes,contact_cellular,contact_telephone,contact_unknown,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,y_no,y_yes
0,0.519481,0.363636,0.092259,0.133333,0.727273,0.053070,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.337662,0.818182,0.073067,0.133333,0.727273,0.030704,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.194805,0.181818,0.072822,0.133333,0.727273,0.015453,0.000000,0.000000,0.000000,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.376623,0.090909,0.086476,0.133333,0.727273,0.018707,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.194805,1.000000,0.072812,0.133333,0.727273,0.040260,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,0.818182,0.080293,0.533333,0.818182,0.198658,0.032258,0.000000,0.000000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
45207,0.688312,0.454545,0.088501,0.533333,0.818182,0.092721,0.016129,0.000000,0.000000,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
45208,0.701299,0.454545,0.124689,0.533333,0.818182,0.229158,0.064516,0.212156,0.010909,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
45209,0.506494,0.090909,0.078868,0.533333,0.818182,0.103294,0.048387,0.000000,0.000000,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
45210,0.246753,0.181818,0.099777,0.533333,0.818182,0.073404,0.016129,0.216743,0.040000,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [21]:
data_scaler(df,num_col)

,age,job,balance,day,month,duration,campaign,pdays,previous,marital_divorced,...,loan_yes,contact_cellular,contact_telephone,contact_unknown,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,y_no,y_yes
0,0.519481,0.363636,0.092259,0.133333,0.727273,0.053070,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.337662,0.818182,0.073067,0.133333,0.727273,0.030704,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.194805,0.181818,0.072822,0.133333,0.727273,0.015453,0.000000,0.000000,0.000000,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.376623,0.090909,0.086476,0.133333,0.727273,0.018707,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.194805,1.000000,0.072812,0.133333,0.727273,0.040260,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,0.818182,0.080293,0.533333,0.818182,0.198658,0.032258,0.000000,0.000000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
45207,0.688312,0.454545,0.088501,0.533333,0.818182,0.092721,0.016129,0.000000,0.000000,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
45208,0.701299,0.454545,0.124689,0.533333,0.818182,0.229158,0.064516,0.212156,0.010909,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
45209,0.506494,0.090909,0.078868,0.533333,0.818182,0.103294,0.048387,0.000000,0.000000,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
45210,0.246753,0.181818,0.099777,0.533333,0.818182,0.073404,0.016129,0.216743,0.040000,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [29]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [23]:
x = df.drop(['y_no', 'y_yes'], axis=1)
y = df['y_yes'].astype(int)

In [28]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2, random_state = 42
)

In [25]:
x_train.shape

(36168, 29)

In [26]:

x_test.shape

(9043, 29)

In [30]:

log_reg.fit(x_train, y_train)

LogisticRegression()

In [31]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = log_reg.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8974897710936636

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.98      0.94      7952
           1       0.66      0.31      0.42      1091

    accuracy                           0.90      9043
   macro avg       0.79      0.64      0.68      9043
weighted avg       0.88      0.90      0.88      9043

Confusion Matrix:
 [[7778  174]
 [ 753  338]]

# function vazifa

In [32]:
def musbat_manfiy(son):
    if son>0:
        return "musbat"
    elif son <0:
        return "manfiy"
    else:
        return "0"
    
musbat_manfiy(44)

'musbat'

In [35]:
def toq_juft(son):
    if son % 2 == 0:
        return "juft"
    else:
        return "toq"
    
toq_juft(11)

'toq'

In [29]:
def son_qosh(a,b):
    return a + b
son_qosh(2,3)

5

In [39]:
def sonlar_royhati(sonlar):
    jami =0
    for son in sonlar:
        jami = jami + son
    return jami
list_son = [10,20,30,30]
print(sonlar_royhati(list_son))

90