MOVIES DATASETI

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('movies.csv')

In [5]:
df.head()

,title,year,rating,votes,runtime,certificate,genre,gross_total
0,The Shawshank Redemption,1994,9.3,"3,168,010",142,R,Drama,$29.33M
1,The Godfather,1972,9.2,"2,212,884",175,R,"Crime, Drama",$250.93M
2,The Dark Knight,2008,9.1,"3,145,646",152,PG-13,"Action, Crime, Drama",$1008.48M
3,The Godfather Part II,1974,9.0,"1,486,878",202,R,"Crime, Drama",$48.20M
4,12 Angry Men,1957,9.0,"977,359",96,Unrated,"Crime, Drama",$0.01M

In [6]:
df.tail()

,title,year,rating,votes,runtime,certificate,genre,gross_total
245,Drishyam,2015,8.2,"107,875",163,Unrated,"Crime, Drama, Mystery",NaN
246,The Grapes of Wrath,1940,8.1,"108,041",129,Unrated,Drama,$0.01M
247,To Be or Not to Be,1942,8.1,"49,586",99,Unrated,"Comedy, Romance, War",$0.00M
248,Gangs of Wasseypur,2012,8.2,"113,517",321,Unrated,"Action, Comedy, Crime",$4.38M
249,Höstsonaten,1978,8.1,"41,972",99,PG,"Drama, Music",$0.04M

In [7]:
df.nunique()

title          250
year            88
rating          14
votes          250
runtime        104
certificate      6
genre          105
gross_total    228
dtype: int64

In [9]:
df[['genre','rating','year']]

                     genre  rating  year
0                    Drama     9.3  1994
1             Crime, Drama     9.2  1972
2     Action, Crime, Drama     9.1  2008
3             Crime, Drama     9.0  1974
4             Crime, Drama     9.0  1957
..                     ...     ...   ...
245  Crime, Drama, Mystery     8.2  2015
246                  Drama     8.1  1940
247   Comedy, Romance, War     8.1  1942
248  Action, Comedy, Crime     8.2  2012
249           Drama, Music     8.1  1978

[250 rows x 3 columns]

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        250 non-null    str
 1   year         250 non-null    int64
 2   rating       250 non-null    float64
 3   votes        250 non-null    str
 4   runtime      250 non-null    int64
 5   certificate  250 non-null    str
 6   genre        250 non-null    str
 7   gross_total  246 non-null    str
dtypes: float64(1), int64(2), str(5)
memory usage: 15.8 KB

In [11]:
df.isnull().sum()

title          0
year           0
rating         0
votes          0
runtime        0
certificate    0
genre          0
gross_total    4
dtype: int64

In [14]:
df.isnull().any()

title          False
year           False
rating         False
votes          False
runtime        False
certificate    False
genre          False
gross_total     True
dtype: bool