# Linear regression uchun loyiha

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('AI_Impact_Student_Life_2026.csv')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               1500 non-null   str
 1   Age                      1500 non-null   int64
 2   Major                    978 non-null    str
 3   Primary_AI_Tool          910 non-null    str
 4   Task_Frequency_Daily     1500 non-null   int64
 5   Main_Usage_Case          1214 non-null   str
 6   GPA_Baseline             1480 non-null   float64
 7   GPA_Post_AI              1354 non-null   float64
 8   Time_Saved_Hours_Weekly  1500 non-null   int64
 9   AI_Ethics_Concern        1500 non-null   str
 10  Career_Confidence_Score  1500 non-null   int64
dtypes: float64(2), int64(4), str(5)
memory usage: 129.0 KB

# Data Preprocessing

Missing

In [ ]:
df.isnull().sum()

Student_ID                   0
Age                          0
Major                      522
Primary_AI_Tool            590
Task_Frequency_Daily         0
Main_Usage_Case            286
GPA_Baseline                20
GPA_Post_AI                146
Time_Saved_Hours_Weekly      0
AI_Ethics_Concern            0
Career_Confidence_Score      0
dtype: int64

In [ ]:
def yigishtir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype =='str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [ ]:
yigishtir(df)
df.isnull().sum()

Student_ID                 0
Age                        0
Major                      0
Primary_AI_Tool            0
Task_Frequency_Daily       0
Main_Usage_Case            0
GPA_Baseline               0
GPA_Post_AI                0
Time_Saved_Hours_Weekly    0
AI_Ethics_Concern          0
Career_Confidence_Score    0
dtype: int64

# Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def encodla(df):
    encoder = LabelEncoder()

    for col in df.columns.to_list(): 
        if df[col].dtype == 'str':
            if df[col].nunique() <= 5:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df.drop(columns=[col], inplace=True)
                df[dummies.columns] = dummies
            else:
                df[col] = encoder.fit_transform(df[col].astype(str))
    
    return df

In [ ]:
df = encodla(df)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Student_ID                         1500 non-null   int64
 1   Age                                1500 non-null   int64
 2   Task_Frequency_Daily               1500 non-null   int64
 3   GPA_Baseline                       1500 non-null   float64
 4   GPA_Post_AI                        1500 non-null   float64
 5   Time_Saved_Hours_Weekly            1500 non-null   int64
 6   Career_Confidence_Score            1500 non-null   int64
 7   Major_Biology                      1500 non-null   int64
 8   Major_Business Administration      1500 non-null   int64
 9   Major_Modern History               1500 non-null   int64
 10  Major_Software Engineering         1500 non-null   int64
 11  Primary_AI_Tool_Claude 3.5         1500 non-null   int64
 12  Primary_AI_Tool_GitHub Copilot     1500 non-null   int64
 13  Primary_AI_Tool_Perplexity         1500 non-null   int64
 14  Main_Usage_Case_Code Debugging     1500 non-null   int64
 15  Main_Usage_Case_Essay Drafting     1500 non-null   int64
 16  Main_Usage_Case_Exam Prep          1500 non-null   int64
 17  Main_Usage_Case_Literature Review  1500 non-null   int64
 18  AI_Ethics_Concern_High             1500 non-null   int64
 19  AI_Ethics_Concern_Low              1500 non-null   int64
 20  AI_Ethics_Concern_Medium           1500 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 246.2 KB

# Scaling

In [ ]:
df.head()

,Student_ID,Age,Task_Frequency_Daily,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,Career_Confidence_Score,Major_Biology,Major_Business Administration,Major_Modern History,...,Primary_AI_Tool_Claude 3.5,Primary_AI_Tool_GitHub Copilot,Primary_AI_Tool_Perplexity,Main_Usage_Case_Code Debugging,Main_Usage_Case_Essay Drafting,Main_Usage_Case_Exam Prep,Main_Usage_Case_Literature Review,AI_Ethics_Concern_High,AI_Ethics_Concern_Low,AI_Ethics_Concern_Medium
0,927,23,1,2.62,2.620000,9,3,0,0,0,...,0,1,0,1,0,0,0,0,0,1
1,1076,22,3,3.99,3.276573,7,4,0,0,1,...,0,1,0,0,1,0,0,0,0,1
2,355,18,2,2.57,2.570000,15,7,1,0,0,...,0,0,1,0,0,0,1,1,0,0
3,205,19,5,2.67,2.870000,12,5,1,0,0,...,1,0,0,0,1,0,0,0,1,0
4,281,19,10,3.65,3.850000,5,9,1,0,0,...,0,1,0,1,0,0,0,1,0,0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('GPA_Post_AI')
    for col in num_col:
        df[col]=scaler.fit_transform(df[[col]])
    return df

In [ ]:
scaling_qil(df)

,Student_ID,Age,Task_Frequency_Daily,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,Career_Confidence_Score,Major_Biology,Major_Business Administration,Major_Modern History,...,Primary_AI_Tool_Claude 3.5,Primary_AI_Tool_GitHub Copilot,Primary_AI_Tool_Perplexity,Main_Usage_Case_Code Debugging,Main_Usage_Case_Essay Drafting,Main_Usage_Case_Exam Prep,Main_Usage_Case_Literature Review,AI_Ethics_Concern_High,AI_Ethics_Concern_Low,AI_Ethics_Concern_Medium
0,0.618412,0.714286,0.000000,0.080537,2.620000,0.538462,0.222222,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.717812,0.571429,0.222222,1.000000,3.276573,0.384615,0.333333,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.236825,0.000000,0.111111,0.046980,2.570000,1.000000,0.666667,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.136758,0.142857,0.444444,0.114094,2.870000,0.769231,0.444444,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.187458,0.142857,1.000000,0.771812,3.850000,0.230769,0.888889,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.280854,0.428571,0.333333,0.570470,3.550000,0.384615,0.666667,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1496,0.513009,0.428571,0.222222,0.731544,3.890000,0.846154,0.666667,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1497,0.018012,0.714286,0.777778,0.469799,3.400000,0.384615,0.111111,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1498,0.454970,0.714286,0.555556,1.000000,3.276573,1.000000,0.666667,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1499,0.488993,0.714286,0.333333,0.691275,3.430000,0.076923,0.777778,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

# Model

In [ ]:
x=df.drop('GPA_Post_AI',axis=1)

In [ ]:
y=df['GPA_Post_AI'].astype(int)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr=LinearRegression()

In [ ]:
lr

LinearRegression()

In [ ]:
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred=lr.predict(x_test)

In [ ]:
y_pred

array([3.07574264, 2.39659827, 2.64386624, 2.36974658, 2.66248145,
       2.94576086, 3.22343028, 2.464367  , 3.18986699, 2.96698775,
       2.40466894, 3.21840836, 3.18084574, 2.71617504, 2.65502027,
       2.20487388, 3.08800483, 2.30340531, 3.21240929, 3.29849007,
       2.78549409, 3.18193969, 2.28277443, 2.79282588, 3.17831908,
       2.89231543, 2.40254011, 2.8995293 , 2.54000249, 2.83354283,
       3.30799957, 2.65938007, 3.16972429, 2.27759533, 2.53334483,
       3.25277639, 3.08269836, 2.38649258, 2.38469954, 2.67770705,
       3.22652746, 2.91480013, 2.82633481, 2.27879719, 3.26199399,
       3.0063606 , 2.72061356, 3.06283708, 2.65031706, 2.7805767 ,
       2.53389812, 2.85215099, 2.92525675, 2.88321698, 2.87701174,
       3.22993479, 3.04463787, 2.20842354, 2.36574153, 2.68908478,
       2.77465822, 3.20334294, 2.64482192, 2.60379515, 2.21052093,
       2.41622396, 2.67757628, 3.12824753, 2.85721719, 2.6043655 ,
       2.58486805, 2.86161579, 3.06118834, 2.36658381, 2.76284219,
       2.39444443, 3.21239792, 2.32384993, 2.59065796, 3.2737632 ,
       3.03755481, 2.41649237, 2.7107666 , 2.99672118, 2.35909835,
       2.94003183, 3.21758123, 2.32323162, 2.42751558, 2.24173565,
       2.54136236, 3.21051055, 3.2905788 , 3.0151578 , 2.26194239,
       3.20648601, 2.96038534, 3.18697853, 2.78741976, 2.29011468,
       2.31507015, 2.80956669, 3.18312194, 2.31324809, 2.57127236,
       2.42709405, 2.20800655, 3.01152746, 2.55677468, 3.29594447,
       2.3525862 , 3.26634684, 2.96507613, 2.41090163, 2.86264149,
       2.60975965, 3.1401896 , 2.62587792, 2.79468775, 2.51493275,
       2.80115109, 3.21379275, 2.88413484, 3.22484549, 2.93598153,
       2.303199  , 2.57732077, 2.94875718, 3.11107654, 2.99537764,
       2.53438238, 3.24270434, 2.95008817, 3.09041814, 2.70067264,
       3.29230602, 3.00461702, 2.31706326, 2.11747683, 2.24305202,
       3.14379849, 2.36136755, 2.22109784, 2.80899523, 2.4617609 ,
       2.5572319 , 2.42911557, 2.37395213, 2.69948207, 2.75257124,
       3.09582645, 2.9322414 , 2.37713882, 3.27952799, 2.22556412,
       2.55479744, 2.75717837, 2.85835267, 2.81241974, 2.41330655,
       2.91679354, 2.27927541, 2.68730579, 3.12528974, 2.41486064,
       2.82279716, 2.16174062, 2.85451864, 2.98005415, 3.07531217,
       3.27816426, 2.8747943 , 2.63222846, 3.02877898, 2.76748977,
       2.7527028 , 2.94665994, 2.49626158, 3.18164261, 2.5752714 ,
       2.31654741, 2.93904542, 2.92221983, 2.52352019, 3.07919673,
       2.9093235 , 2.78452687, 2.89611658, 3.12465358, 2.75818688,
       2.27241346, 2.85216161, 3.00558536, 3.29769306, 2.71385518,
       2.44345078, 2.88730857, 2.66582529, 2.28823505, 2.59196214,
       2.3851337 , 2.17778918, 2.79763279, 3.08257672, 2.31244405,
       3.2893102 , 2.32542747, 2.82300934, 3.0839373 , 2.29102971,
       2.45405326, 2.82977101, 2.66095495, 3.37912174, 3.21364503,
       3.14218852, 3.07393682, 2.27090442, 2.69101598, 3.01491435,
       2.55744835, 2.67205302, 2.30020813, 2.78593262, 2.89711562,
       2.75960386, 2.65752832, 2.16272465, 2.53943533, 2.73579092,
       3.18460033, 3.10195921, 2.70852814, 2.32782314, 2.64749398,
       3.15200388, 2.98662282, 2.57669352, 2.94827023, 2.34740949,
       2.34768961, 2.22219817, 2.35634328, 2.49557585, 2.48171275,
       2.53452211, 3.24632328, 2.73776625, 2.82605492, 2.98389117,
       2.96305765, 3.26762287, 2.78210929, 3.22377721, 2.68836904,
       2.91384737, 3.04544113, 2.63825731, 2.68199543, 2.28224867,
       2.53907491, 2.69755495, 2.82593604, 2.92687785, 2.87313692,
       2.19419689, 2.40356417, 2.41161382, 2.3730442 , 2.81472171,
       3.16196229, 3.23164872, 2.33832818, 2.77020335, 2.23243947,
       2.23826065, 2.18623264, 2.71353408, 2.94291352, 2.3865679 ,
       2.4379984 , 2.84768589, 2.72590003, 2.6667428 , 3.00146027,
       2.7596243 , 2.27940468, 2.75149069, 3.16213029, 2.79786009,
       2.36033114, 3.0224368 , 2.49245516, 2.4543669 , 2.69946018,
       2.67914602, 2.83831641, 2.25550723, 3.17413451, 2.38684275,
       2.95839633, 3.03020345, 2.39385279, 2.21196846, 2.55093328,
       3.0330763 , 2.52608688, 2.66661997, 2.2884136 , 2.5179076 ,
       2.47949737, 2.31072729, 2.40938909, 3.00787429, 2.74982699,
       2.63981031, 2.40082252, 2.3773236 , 3.31915727, 2.3237734 ,
       2.9192914 , 2.80941518, 3.18457643, 2.82190451, 2.29517058,
       2.2196377 , 2.57264204, 2.77042502, 2.99259845, 2.31186571,
       3.0840755 , 2.57806627, 2.82485861, 2.6302233 , 2.23634223,
       3.21467251, 2.48862334, 2.70058086, 2.46168421, 2.59356218,
       2.9289095 , 2.44125011, 2.61669171, 2.82714776, 3.20206524,
       2.94435212, 2.88103983, 3.18821128, 2.75676541, 2.44667372,
       2.8700969 , 2.90470529, 2.8241882 , 2.67596483, 3.17917023,
       3.03215836, 3.00864338, 3.08928347, 2.67042403, 2.53293037,
       2.83745939, 2.27629292, 2.89100511, 3.02807392, 3.26629977,
       2.78518393, 2.30240568, 2.95583273, 3.12240357, 2.58616985,
       3.15295959, 3.10324921, 2.2950459 , 2.38012243, 2.78886874,
       3.22382481, 2.968202  , 3.05829423, 2.88587262, 2.54675906,
       2.89203333, 2.38826148, 2.73259111, 2.83242388, 2.75362948,
       2.38266054, 3.17773582, 2.8403816 , 3.09433315, 3.37311272,
       3.29011012, 2.62000551, 2.29152282, 3.1325016 , 3.31425797,
       3.25083492, 3.05534716, 3.19831234, 3.00925571, 2.35251702,
       3.14304328, 3.14400638, 3.03890162, 2.25558823, 2.66929041,
       2.41017451, 3.11816608, 2.50998038, 2.28790326, 3.28471618,
       2.5595707 , 3.20661274, 2.85800633, 2.63360797, 2.29850556,
       2.20976975, 2.85720637, 3.20116095, 2.48916679, 2.47305612,
       2.94645759, 2.95413905, 2.21548858, 2.80806517, 2.57954134,
       2.6927211 , 3.15179731, 2.72148647, 2.94518297, 2.59146239,
       2.99337552, 3.17988379, 3.21489437, 2.30633405, 2.47281804,
       2.90298238, 2.38256988, 2.46537546, 2.77845075, 2.45605945,
       3.09447567, 2.66989709, 3.1238601 , 2.24191629, 2.5194757 ,
       2.45548742, 3.28459756, 2.37576124, 2.82350718, 3.30931364])

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [ ]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_pred)

In [ ]:
print('r2',r2)
print('mse',mse)
print('rmse',rmse)
print('mae',mae)

r2 0.5385534714794487
mse 0.09118639153223894
rmse 0.3019708455004207
mae 0.25945450856459956