# Model building

# Data bilan tanishuv

In [28]:
import pandas as pd 
df=pd.read_csv('tested.csv')

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    str
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 39.3 KB

In [30]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

# Filling missing values

In [31]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype == 'object':
                df[col] = df[col].fillna(df[col].mode()[0])
            elif df[col].dtype in ['int64', 'float64']:
                df[col] = df[col].fillna(df[col].median())
            else:
                df[col] = df[col].fillna(0)
    return df

In [32]:
toldir(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,0,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,0,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,0,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,0,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,0,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,0,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,0,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,0,C

In [33]:
df['PassengerId'].value_counts()

PassengerId
892     1
893     1
894     1
895     1
896     1
       ..
1305    1
1306    1
1307    1
1308    1
1309    1
Name: count, Length: 418, dtype: int64

In [34]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# Dropping

In [35]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Pclass    418 non-null    int64
 2   Sex       418 non-null    str
 3   Age       418 non-null    float64
 4   SibSp     418 non-null    int64
 5   Parch     418 non-null    int64
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    str
dtypes: float64(2), int64(4), str(2)
memory usage: 26.2 KB

In [37]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

# Encoding

In [38]:
df = pd.get_dummies(df, drop_first=True)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    418 non-null    int64
 1   Pclass      418 non-null    int64
 2   Age         418 non-null    float64
 3   SibSp       418 non-null    int64
 4   Parch       418 non-null    int64
 5   Fare        418 non-null    float64
 6   Sex_male    418 non-null    bool
 7   Embarked_Q  418 non-null    bool
 8   Embarked_S  418 non-null    bool
dtypes: bool(3), float64(2), int64(4)
memory usage: 20.9 KB

In [40]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    418 non-null    int64
 1   Pclass      418 non-null    int64
 2   Age         418 non-null    float64
 3   SibSp       418 non-null    int64
 4   Parch       418 non-null    int64
 5   Fare        418 non-null    float64
 6   Sex_male    418 non-null    int64
 7   Embarked_Q  418 non-null    int64
 8   Embarked_S  418 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 29.5 KB

# Scaler

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
minmax_scaler=MinMaxScaler()

In [44]:
minmax_scaler

MinMaxScaler()

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    418 non-null    int64
 1   Pclass      418 non-null    int64
 2   Age         418 non-null    float64
 3   SibSp       418 non-null    int64
 4   Parch       418 non-null    int64
 5   Fare        418 non-null    float64
 6   Sex_male    418 non-null    int64
 7   Embarked_Q  418 non-null    int64
 8   Embarked_S  418 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 29.5 KB

In [46]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns

In [47]:
print(num_col)

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male',
       'Embarked_Q', 'Embarked_S'],
      dtype='str')

In [2]:
df[num_col] = minmax_scaler.fit_transform(df[num_col])

NameError: name 'minmax_scaler' is not defined

In [49]:
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0.0,1.0,0.452723,0.000,0.000000,0.015282,1.0,1.0,0.0
1,1.0,1.0,0.617566,0.125,0.000000,0.013663,0.0,0.0,1.0
2,0.0,0.5,0.815377,0.000,0.000000,0.018909,1.0,1.0,0.0
3,0.0,1.0,0.353818,0.000,0.000000,0.016908,1.0,0.0,1.0
4,1.0,1.0,0.287881,0.125,0.111111,0.023984,0.0,0.0,1.0

# Feature va targetga ajratish

In [50]:
x = df.drop(columns='Survived')

In [51]:
y= df['Survived']

In [52]:
y

0      0.0
1      1.0
2      0.0
3      0.0
4      1.0
      ...
413    0.0
414    1.0
415    0.0
416    0.0
417    0.0
Name: Survived, Length: 418, dtype: float64

# Train va test split

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [55]:
x_train.shape

(334, 8)

In [56]:
x_test.shape

(84, 8)

In [57]:
y_train.shape

(334,)

In [58]:
y_test.shape

(84,)

# Logistik Regression

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
model=LogisticRegression()

In [61]:
model

LogisticRegression()

In [62]:
model.fit(x_train,y_train)

LogisticRegression()

# Prediction

In [63]:
y_predection=model.predict(x_test)

In [64]:
y_predection

array([0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1.])

# Evoluation

In [65]:
from sklearn.metrics import accuracy_score

In [66]:
accuracy=accuracy_score(y_test,y_predection)

In [67]:
print('Accuracy:', accuracy_score(y_test, y_predection))

Accuracy: 1.0